
// Imports
import * as _0_0 from "@api/root/src/api/v1/agents/index.ts";
import * as _0_1 from "@api/root/src/api/v1/agents/[id].ts";
import * as _0_2 from "@api/root/src/api/v1/auth/index.ts";
import * as _0_3 from "@api/root/src/api/v1/backups/index.ts";
import * as _0_4 from "@api/root/src/api/v1/car/index.ts";
import * as _0_5 from "@api/root/src/api/v1/car/[id].ts";
import * as _0_6 from "@api/root/src/api/v1/cases/index.ts";
import * as _0_7 from "@api/root/src/api/v1/cases/[id].ts";
import * as _0_8 from "@api/root/src/api/v1/civilians/index.ts";
import * as _0_9 from "@api/root/src/api/v1/civilians/[id].ts";
import * as _0_10 from "@api/root/src/api/v1/criminalCase/index.ts";
import * as _0_11 from "@api/root/src/api/v1/criminalCase/[id].ts";
import * as _0_12 from "@api/root/src/api/v1/criminalRecord/index.ts";
import * as _0_13 from "@api/root/src/api/v1/criminalRecord/[id].ts";
import * as _0_14 from "@api/root/src/api/v1/dispatch/index.ts";
import * as _0_15 from "@api/root/src/api/v1/dispatch/[id].ts";
import * as _0_16 from "@api/root/src/api/v1/entities/index.ts";
import * as _0_17 from "@api/root/src/api/v1/entities/[id].ts";
import * as _0_18 from "@api/root/src/api/v1/evidences/index.ts";
import * as _0_19 from "@api/root/src/api/v1/evidences/[id].ts";
import * as _0_20 from "@api/root/src/api/v1/grade/index.ts";
import * as _0_21 from "@api/root/src/api/v1/grade/[id].ts";
import * as _0_22 from "@api/root/src/api/v1/homicide/index.ts";
import * as _0_23 from "@api/root/src/api/v1/homicide/[id].ts";
import * as _0_24 from "@api/root/src/api/v1/licences/index.ts";
import * as _0_25 from "@api/root/src/api/v1/licences/[id].ts";
import * as _0_26 from "@api/root/src/api/v1/reports/index.ts";
import * as _0_27 from "@api/root/src/api/v1/reports/[id].ts";
import * as _0_28 from "@api/root/src/api/v1/sanctions/index.ts";
import * as _0_29 from "@api/root/src/api/v1/sanctions/[id].ts";
import * as _0_30 from "@api/root/src/api/v1/suspects/index.ts";
import * as _0_31 from "@api/root/src/api/v1/suspects/[id].ts";
import * as _0_32 from "@api/root/src/api/v1/weapons/index.ts";
import * as _0_33 from "@api/root/src/api/v1/weapons/[id].ts";
import * as configure from "@api/configure";

export const routeBase = "/api";

const internal  = [
  _0_0.default && {
        source     : "src/api/v1/agents/index.ts?fn=default",
        method     : "use",
        route      : "/agents/",
        path       : "/api/agents/",
        url        : "/api/agents/",
        cb         : _0_0.default,
      },
  _0_0.GET && {
        source     : "src/api/v1/agents/index.ts?fn=GET",
        method     : "get",
        route      : "/agents/",
        path       : "/api/agents/",
        url        : "/api/agents/",
        cb         : _0_0.GET,
      },
  _0_0.PUT && {
        source     : "src/api/v1/agents/index.ts?fn=PUT",
        method     : "put",
        route      : "/agents/",
        path       : "/api/agents/",
        url        : "/api/agents/",
        cb         : _0_0.PUT,
      },
  _0_0.POST && {
        source     : "src/api/v1/agents/index.ts?fn=POST",
        method     : "post",
        route      : "/agents/",
        path       : "/api/agents/",
        url        : "/api/agents/",
        cb         : _0_0.POST,
      },
  _0_0.PATCH && {
        source     : "src/api/v1/agents/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/agents/",
        path       : "/api/agents/",
        url        : "/api/agents/",
        cb         : _0_0.PATCH,
      },
  _0_0.DELETE && {
        source     : "src/api/v1/agents/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/agents/",
        path       : "/api/agents/",
        url        : "/api/agents/",
        cb         : _0_0.DELETE,
      },
  _0_1.default && {
        source     : "src/api/v1/agents/[id].ts?fn=default",
        method     : "use",
        route      : "/agents/:id",
        path       : "/api/agents/:id",
        url        : "/api/agents/:id",
        cb         : _0_1.default,
      },
  _0_1.GET && {
        source     : "src/api/v1/agents/[id].ts?fn=GET",
        method     : "get",
        route      : "/agents/:id",
        path       : "/api/agents/:id",
        url        : "/api/agents/:id",
        cb         : _0_1.GET,
      },
  _0_1.PUT && {
        source     : "src/api/v1/agents/[id].ts?fn=PUT",
        method     : "put",
        route      : "/agents/:id",
        path       : "/api/agents/:id",
        url        : "/api/agents/:id",
        cb         : _0_1.PUT,
      },
  _0_1.POST && {
        source     : "src/api/v1/agents/[id].ts?fn=POST",
        method     : "post",
        route      : "/agents/:id",
        path       : "/api/agents/:id",
        url        : "/api/agents/:id",
        cb         : _0_1.POST,
      },
  _0_1.PATCH && {
        source     : "src/api/v1/agents/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/agents/:id",
        path       : "/api/agents/:id",
        url        : "/api/agents/:id",
        cb         : _0_1.PATCH,
      },
  _0_1.DELETE && {
        source     : "src/api/v1/agents/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/agents/:id",
        path       : "/api/agents/:id",
        url        : "/api/agents/:id",
        cb         : _0_1.DELETE,
      },
  _0_2.default && {
        source     : "src/api/v1/auth/index.ts?fn=default",
        method     : "use",
        route      : "/auth/",
        path       : "/api/auth/",
        url        : "/api/auth/",
        cb         : _0_2.default,
      },
  _0_2.GET && {
        source     : "src/api/v1/auth/index.ts?fn=GET",
        method     : "get",
        route      : "/auth/",
        path       : "/api/auth/",
        url        : "/api/auth/",
        cb         : _0_2.GET,
      },
  _0_2.PUT && {
        source     : "src/api/v1/auth/index.ts?fn=PUT",
        method     : "put",
        route      : "/auth/",
        path       : "/api/auth/",
        url        : "/api/auth/",
        cb         : _0_2.PUT,
      },
  _0_2.POST && {
        source     : "src/api/v1/auth/index.ts?fn=POST",
        method     : "post",
        route      : "/auth/",
        path       : "/api/auth/",
        url        : "/api/auth/",
        cb         : _0_2.POST,
      },
  _0_2.PATCH && {
        source     : "src/api/v1/auth/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/auth/",
        path       : "/api/auth/",
        url        : "/api/auth/",
        cb         : _0_2.PATCH,
      },
  _0_2.DELETE && {
        source     : "src/api/v1/auth/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/auth/",
        path       : "/api/auth/",
        url        : "/api/auth/",
        cb         : _0_2.DELETE,
      },
  _0_3.default && {
        source     : "src/api/v1/backups/index.ts?fn=default",
        method     : "use",
        route      : "/backups/",
        path       : "/api/backups/",
        url        : "/api/backups/",
        cb         : _0_3.default,
      },
  _0_3.GET && {
        source     : "src/api/v1/backups/index.ts?fn=GET",
        method     : "get",
        route      : "/backups/",
        path       : "/api/backups/",
        url        : "/api/backups/",
        cb         : _0_3.GET,
      },
  _0_3.PUT && {
        source     : "src/api/v1/backups/index.ts?fn=PUT",
        method     : "put",
        route      : "/backups/",
        path       : "/api/backups/",
        url        : "/api/backups/",
        cb         : _0_3.PUT,
      },
  _0_3.POST && {
        source     : "src/api/v1/backups/index.ts?fn=POST",
        method     : "post",
        route      : "/backups/",
        path       : "/api/backups/",
        url        : "/api/backups/",
        cb         : _0_3.POST,
      },
  _0_3.PATCH && {
        source     : "src/api/v1/backups/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/backups/",
        path       : "/api/backups/",
        url        : "/api/backups/",
        cb         : _0_3.PATCH,
      },
  _0_3.DELETE && {
        source     : "src/api/v1/backups/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/backups/",
        path       : "/api/backups/",
        url        : "/api/backups/",
        cb         : _0_3.DELETE,
      },
  _0_4.default && {
        source     : "src/api/v1/car/index.ts?fn=default",
        method     : "use",
        route      : "/car/",
        path       : "/api/car/",
        url        : "/api/car/",
        cb         : _0_4.default,
      },
  _0_4.GET && {
        source     : "src/api/v1/car/index.ts?fn=GET",
        method     : "get",
        route      : "/car/",
        path       : "/api/car/",
        url        : "/api/car/",
        cb         : _0_4.GET,
      },
  _0_4.PUT && {
        source     : "src/api/v1/car/index.ts?fn=PUT",
        method     : "put",
        route      : "/car/",
        path       : "/api/car/",
        url        : "/api/car/",
        cb         : _0_4.PUT,
      },
  _0_4.POST && {
        source     : "src/api/v1/car/index.ts?fn=POST",
        method     : "post",
        route      : "/car/",
        path       : "/api/car/",
        url        : "/api/car/",
        cb         : _0_4.POST,
      },
  _0_4.PATCH && {
        source     : "src/api/v1/car/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/car/",
        path       : "/api/car/",
        url        : "/api/car/",
        cb         : _0_4.PATCH,
      },
  _0_4.DELETE && {
        source     : "src/api/v1/car/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/car/",
        path       : "/api/car/",
        url        : "/api/car/",
        cb         : _0_4.DELETE,
      },
  _0_5.default && {
        source     : "src/api/v1/car/[id].ts?fn=default",
        method     : "use",
        route      : "/car/:id",
        path       : "/api/car/:id",
        url        : "/api/car/:id",
        cb         : _0_5.default,
      },
  _0_5.GET && {
        source     : "src/api/v1/car/[id].ts?fn=GET",
        method     : "get",
        route      : "/car/:id",
        path       : "/api/car/:id",
        url        : "/api/car/:id",
        cb         : _0_5.GET,
      },
  _0_5.PUT && {
        source     : "src/api/v1/car/[id].ts?fn=PUT",
        method     : "put",
        route      : "/car/:id",
        path       : "/api/car/:id",
        url        : "/api/car/:id",
        cb         : _0_5.PUT,
      },
  _0_5.POST && {
        source     : "src/api/v1/car/[id].ts?fn=POST",
        method     : "post",
        route      : "/car/:id",
        path       : "/api/car/:id",
        url        : "/api/car/:id",
        cb         : _0_5.POST,
      },
  _0_5.PATCH && {
        source     : "src/api/v1/car/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/car/:id",
        path       : "/api/car/:id",
        url        : "/api/car/:id",
        cb         : _0_5.PATCH,
      },
  _0_5.DELETE && {
        source     : "src/api/v1/car/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/car/:id",
        path       : "/api/car/:id",
        url        : "/api/car/:id",
        cb         : _0_5.DELETE,
      },
  _0_6.default && {
        source     : "src/api/v1/cases/index.ts?fn=default",
        method     : "use",
        route      : "/cases/",
        path       : "/api/cases/",
        url        : "/api/cases/",
        cb         : _0_6.default,
      },
  _0_6.GET && {
        source     : "src/api/v1/cases/index.ts?fn=GET",
        method     : "get",
        route      : "/cases/",
        path       : "/api/cases/",
        url        : "/api/cases/",
        cb         : _0_6.GET,
      },
  _0_6.PUT && {
        source     : "src/api/v1/cases/index.ts?fn=PUT",
        method     : "put",
        route      : "/cases/",
        path       : "/api/cases/",
        url        : "/api/cases/",
        cb         : _0_6.PUT,
      },
  _0_6.POST && {
        source     : "src/api/v1/cases/index.ts?fn=POST",
        method     : "post",
        route      : "/cases/",
        path       : "/api/cases/",
        url        : "/api/cases/",
        cb         : _0_6.POST,
      },
  _0_6.PATCH && {
        source     : "src/api/v1/cases/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/cases/",
        path       : "/api/cases/",
        url        : "/api/cases/",
        cb         : _0_6.PATCH,
      },
  _0_6.DELETE && {
        source     : "src/api/v1/cases/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/cases/",
        path       : "/api/cases/",
        url        : "/api/cases/",
        cb         : _0_6.DELETE,
      },
  _0_7.default && {
        source     : "src/api/v1/cases/[id].ts?fn=default",
        method     : "use",
        route      : "/cases/:id",
        path       : "/api/cases/:id",
        url        : "/api/cases/:id",
        cb         : _0_7.default,
      },
  _0_7.GET && {
        source     : "src/api/v1/cases/[id].ts?fn=GET",
        method     : "get",
        route      : "/cases/:id",
        path       : "/api/cases/:id",
        url        : "/api/cases/:id",
        cb         : _0_7.GET,
      },
  _0_7.PUT && {
        source     : "src/api/v1/cases/[id].ts?fn=PUT",
        method     : "put",
        route      : "/cases/:id",
        path       : "/api/cases/:id",
        url        : "/api/cases/:id",
        cb         : _0_7.PUT,
      },
  _0_7.POST && {
        source     : "src/api/v1/cases/[id].ts?fn=POST",
        method     : "post",
        route      : "/cases/:id",
        path       : "/api/cases/:id",
        url        : "/api/cases/:id",
        cb         : _0_7.POST,
      },
  _0_7.PATCH && {
        source     : "src/api/v1/cases/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/cases/:id",
        path       : "/api/cases/:id",
        url        : "/api/cases/:id",
        cb         : _0_7.PATCH,
      },
  _0_7.DELETE && {
        source     : "src/api/v1/cases/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/cases/:id",
        path       : "/api/cases/:id",
        url        : "/api/cases/:id",
        cb         : _0_7.DELETE,
      },
  _0_8.default && {
        source     : "src/api/v1/civilians/index.ts?fn=default",
        method     : "use",
        route      : "/civilians/",
        path       : "/api/civilians/",
        url        : "/api/civilians/",
        cb         : _0_8.default,
      },
  _0_8.GET && {
        source     : "src/api/v1/civilians/index.ts?fn=GET",
        method     : "get",
        route      : "/civilians/",
        path       : "/api/civilians/",
        url        : "/api/civilians/",
        cb         : _0_8.GET,
      },
  _0_8.PUT && {
        source     : "src/api/v1/civilians/index.ts?fn=PUT",
        method     : "put",
        route      : "/civilians/",
        path       : "/api/civilians/",
        url        : "/api/civilians/",
        cb         : _0_8.PUT,
      },
  _0_8.POST && {
        source     : "src/api/v1/civilians/index.ts?fn=POST",
        method     : "post",
        route      : "/civilians/",
        path       : "/api/civilians/",
        url        : "/api/civilians/",
        cb         : _0_8.POST,
      },
  _0_8.PATCH && {
        source     : "src/api/v1/civilians/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/civilians/",
        path       : "/api/civilians/",
        url        : "/api/civilians/",
        cb         : _0_8.PATCH,
      },
  _0_8.DELETE && {
        source     : "src/api/v1/civilians/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/civilians/",
        path       : "/api/civilians/",
        url        : "/api/civilians/",
        cb         : _0_8.DELETE,
      },
  _0_9.default && {
        source     : "src/api/v1/civilians/[id].ts?fn=default",
        method     : "use",
        route      : "/civilians/:id",
        path       : "/api/civilians/:id",
        url        : "/api/civilians/:id",
        cb         : _0_9.default,
      },
  _0_9.GET && {
        source     : "src/api/v1/civilians/[id].ts?fn=GET",
        method     : "get",
        route      : "/civilians/:id",
        path       : "/api/civilians/:id",
        url        : "/api/civilians/:id",
        cb         : _0_9.GET,
      },
  _0_9.PUT && {
        source     : "src/api/v1/civilians/[id].ts?fn=PUT",
        method     : "put",
        route      : "/civilians/:id",
        path       : "/api/civilians/:id",
        url        : "/api/civilians/:id",
        cb         : _0_9.PUT,
      },
  _0_9.POST && {
        source     : "src/api/v1/civilians/[id].ts?fn=POST",
        method     : "post",
        route      : "/civilians/:id",
        path       : "/api/civilians/:id",
        url        : "/api/civilians/:id",
        cb         : _0_9.POST,
      },
  _0_9.PATCH && {
        source     : "src/api/v1/civilians/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/civilians/:id",
        path       : "/api/civilians/:id",
        url        : "/api/civilians/:id",
        cb         : _0_9.PATCH,
      },
  _0_9.DELETE && {
        source     : "src/api/v1/civilians/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/civilians/:id",
        path       : "/api/civilians/:id",
        url        : "/api/civilians/:id",
        cb         : _0_9.DELETE,
      },
  _0_10.default && {
        source     : "src/api/v1/criminalCase/index.ts?fn=default",
        method     : "use",
        route      : "/criminalCase/",
        path       : "/api/criminalCase/",
        url        : "/api/criminalCase/",
        cb         : _0_10.default,
      },
  _0_10.GET && {
        source     : "src/api/v1/criminalCase/index.ts?fn=GET",
        method     : "get",
        route      : "/criminalCase/",
        path       : "/api/criminalCase/",
        url        : "/api/criminalCase/",
        cb         : _0_10.GET,
      },
  _0_10.PUT && {
        source     : "src/api/v1/criminalCase/index.ts?fn=PUT",
        method     : "put",
        route      : "/criminalCase/",
        path       : "/api/criminalCase/",
        url        : "/api/criminalCase/",
        cb         : _0_10.PUT,
      },
  _0_10.POST && {
        source     : "src/api/v1/criminalCase/index.ts?fn=POST",
        method     : "post",
        route      : "/criminalCase/",
        path       : "/api/criminalCase/",
        url        : "/api/criminalCase/",
        cb         : _0_10.POST,
      },
  _0_10.PATCH && {
        source     : "src/api/v1/criminalCase/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/criminalCase/",
        path       : "/api/criminalCase/",
        url        : "/api/criminalCase/",
        cb         : _0_10.PATCH,
      },
  _0_10.DELETE && {
        source     : "src/api/v1/criminalCase/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/criminalCase/",
        path       : "/api/criminalCase/",
        url        : "/api/criminalCase/",
        cb         : _0_10.DELETE,
      },
  _0_11.default && {
        source     : "src/api/v1/criminalCase/[id].ts?fn=default",
        method     : "use",
        route      : "/criminalCase/:id",
        path       : "/api/criminalCase/:id",
        url        : "/api/criminalCase/:id",
        cb         : _0_11.default,
      },
  _0_11.GET && {
        source     : "src/api/v1/criminalCase/[id].ts?fn=GET",
        method     : "get",
        route      : "/criminalCase/:id",
        path       : "/api/criminalCase/:id",
        url        : "/api/criminalCase/:id",
        cb         : _0_11.GET,
      },
  _0_11.PUT && {
        source     : "src/api/v1/criminalCase/[id].ts?fn=PUT",
        method     : "put",
        route      : "/criminalCase/:id",
        path       : "/api/criminalCase/:id",
        url        : "/api/criminalCase/:id",
        cb         : _0_11.PUT,
      },
  _0_11.POST && {
        source     : "src/api/v1/criminalCase/[id].ts?fn=POST",
        method     : "post",
        route      : "/criminalCase/:id",
        path       : "/api/criminalCase/:id",
        url        : "/api/criminalCase/:id",
        cb         : _0_11.POST,
      },
  _0_11.PATCH && {
        source     : "src/api/v1/criminalCase/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/criminalCase/:id",
        path       : "/api/criminalCase/:id",
        url        : "/api/criminalCase/:id",
        cb         : _0_11.PATCH,
      },
  _0_11.DELETE && {
        source     : "src/api/v1/criminalCase/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/criminalCase/:id",
        path       : "/api/criminalCase/:id",
        url        : "/api/criminalCase/:id",
        cb         : _0_11.DELETE,
      },
  _0_12.default && {
        source     : "src/api/v1/criminalRecord/index.ts?fn=default",
        method     : "use",
        route      : "/criminalRecord/",
        path       : "/api/criminalRecord/",
        url        : "/api/criminalRecord/",
        cb         : _0_12.default,
      },
  _0_12.GET && {
        source     : "src/api/v1/criminalRecord/index.ts?fn=GET",
        method     : "get",
        route      : "/criminalRecord/",
        path       : "/api/criminalRecord/",
        url        : "/api/criminalRecord/",
        cb         : _0_12.GET,
      },
  _0_12.PUT && {
        source     : "src/api/v1/criminalRecord/index.ts?fn=PUT",
        method     : "put",
        route      : "/criminalRecord/",
        path       : "/api/criminalRecord/",
        url        : "/api/criminalRecord/",
        cb         : _0_12.PUT,
      },
  _0_12.POST && {
        source     : "src/api/v1/criminalRecord/index.ts?fn=POST",
        method     : "post",
        route      : "/criminalRecord/",
        path       : "/api/criminalRecord/",
        url        : "/api/criminalRecord/",
        cb         : _0_12.POST,
      },
  _0_12.PATCH && {
        source     : "src/api/v1/criminalRecord/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/criminalRecord/",
        path       : "/api/criminalRecord/",
        url        : "/api/criminalRecord/",
        cb         : _0_12.PATCH,
      },
  _0_12.DELETE && {
        source     : "src/api/v1/criminalRecord/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/criminalRecord/",
        path       : "/api/criminalRecord/",
        url        : "/api/criminalRecord/",
        cb         : _0_12.DELETE,
      },
  _0_13.default && {
        source     : "src/api/v1/criminalRecord/[id].ts?fn=default",
        method     : "use",
        route      : "/criminalRecord/:id",
        path       : "/api/criminalRecord/:id",
        url        : "/api/criminalRecord/:id",
        cb         : _0_13.default,
      },
  _0_13.GET && {
        source     : "src/api/v1/criminalRecord/[id].ts?fn=GET",
        method     : "get",
        route      : "/criminalRecord/:id",
        path       : "/api/criminalRecord/:id",
        url        : "/api/criminalRecord/:id",
        cb         : _0_13.GET,
      },
  _0_13.PUT && {
        source     : "src/api/v1/criminalRecord/[id].ts?fn=PUT",
        method     : "put",
        route      : "/criminalRecord/:id",
        path       : "/api/criminalRecord/:id",
        url        : "/api/criminalRecord/:id",
        cb         : _0_13.PUT,
      },
  _0_13.POST && {
        source     : "src/api/v1/criminalRecord/[id].ts?fn=POST",
        method     : "post",
        route      : "/criminalRecord/:id",
        path       : "/api/criminalRecord/:id",
        url        : "/api/criminalRecord/:id",
        cb         : _0_13.POST,
      },
  _0_13.PATCH && {
        source     : "src/api/v1/criminalRecord/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/criminalRecord/:id",
        path       : "/api/criminalRecord/:id",
        url        : "/api/criminalRecord/:id",
        cb         : _0_13.PATCH,
      },
  _0_13.DELETE && {
        source     : "src/api/v1/criminalRecord/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/criminalRecord/:id",
        path       : "/api/criminalRecord/:id",
        url        : "/api/criminalRecord/:id",
        cb         : _0_13.DELETE,
      },
  _0_14.default && {
        source     : "src/api/v1/dispatch/index.ts?fn=default",
        method     : "use",
        route      : "/dispatch/",
        path       : "/api/dispatch/",
        url        : "/api/dispatch/",
        cb         : _0_14.default,
      },
  _0_14.GET && {
        source     : "src/api/v1/dispatch/index.ts?fn=GET",
        method     : "get",
        route      : "/dispatch/",
        path       : "/api/dispatch/",
        url        : "/api/dispatch/",
        cb         : _0_14.GET,
      },
  _0_14.PUT && {
        source     : "src/api/v1/dispatch/index.ts?fn=PUT",
        method     : "put",
        route      : "/dispatch/",
        path       : "/api/dispatch/",
        url        : "/api/dispatch/",
        cb         : _0_14.PUT,
      },
  _0_14.POST && {
        source     : "src/api/v1/dispatch/index.ts?fn=POST",
        method     : "post",
        route      : "/dispatch/",
        path       : "/api/dispatch/",
        url        : "/api/dispatch/",
        cb         : _0_14.POST,
      },
  _0_14.PATCH && {
        source     : "src/api/v1/dispatch/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/dispatch/",
        path       : "/api/dispatch/",
        url        : "/api/dispatch/",
        cb         : _0_14.PATCH,
      },
  _0_14.DELETE && {
        source     : "src/api/v1/dispatch/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/dispatch/",
        path       : "/api/dispatch/",
        url        : "/api/dispatch/",
        cb         : _0_14.DELETE,
      },
  _0_15.default && {
        source     : "src/api/v1/dispatch/[id].ts?fn=default",
        method     : "use",
        route      : "/dispatch/:id",
        path       : "/api/dispatch/:id",
        url        : "/api/dispatch/:id",
        cb         : _0_15.default,
      },
  _0_15.GET && {
        source     : "src/api/v1/dispatch/[id].ts?fn=GET",
        method     : "get",
        route      : "/dispatch/:id",
        path       : "/api/dispatch/:id",
        url        : "/api/dispatch/:id",
        cb         : _0_15.GET,
      },
  _0_15.PUT && {
        source     : "src/api/v1/dispatch/[id].ts?fn=PUT",
        method     : "put",
        route      : "/dispatch/:id",
        path       : "/api/dispatch/:id",
        url        : "/api/dispatch/:id",
        cb         : _0_15.PUT,
      },
  _0_15.POST && {
        source     : "src/api/v1/dispatch/[id].ts?fn=POST",
        method     : "post",
        route      : "/dispatch/:id",
        path       : "/api/dispatch/:id",
        url        : "/api/dispatch/:id",
        cb         : _0_15.POST,
      },
  _0_15.PATCH && {
        source     : "src/api/v1/dispatch/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/dispatch/:id",
        path       : "/api/dispatch/:id",
        url        : "/api/dispatch/:id",
        cb         : _0_15.PATCH,
      },
  _0_15.DELETE && {
        source     : "src/api/v1/dispatch/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/dispatch/:id",
        path       : "/api/dispatch/:id",
        url        : "/api/dispatch/:id",
        cb         : _0_15.DELETE,
      },
  _0_16.default && {
        source     : "src/api/v1/entities/index.ts?fn=default",
        method     : "use",
        route      : "/entities/",
        path       : "/api/entities/",
        url        : "/api/entities/",
        cb         : _0_16.default,
      },
  _0_16.GET && {
        source     : "src/api/v1/entities/index.ts?fn=GET",
        method     : "get",
        route      : "/entities/",
        path       : "/api/entities/",
        url        : "/api/entities/",
        cb         : _0_16.GET,
      },
  _0_16.PUT && {
        source     : "src/api/v1/entities/index.ts?fn=PUT",
        method     : "put",
        route      : "/entities/",
        path       : "/api/entities/",
        url        : "/api/entities/",
        cb         : _0_16.PUT,
      },
  _0_16.POST && {
        source     : "src/api/v1/entities/index.ts?fn=POST",
        method     : "post",
        route      : "/entities/",
        path       : "/api/entities/",
        url        : "/api/entities/",
        cb         : _0_16.POST,
      },
  _0_16.PATCH && {
        source     : "src/api/v1/entities/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/entities/",
        path       : "/api/entities/",
        url        : "/api/entities/",
        cb         : _0_16.PATCH,
      },
  _0_16.DELETE && {
        source     : "src/api/v1/entities/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/entities/",
        path       : "/api/entities/",
        url        : "/api/entities/",
        cb         : _0_16.DELETE,
      },
  _0_17.default && {
        source     : "src/api/v1/entities/[id].ts?fn=default",
        method     : "use",
        route      : "/entities/:id",
        path       : "/api/entities/:id",
        url        : "/api/entities/:id",
        cb         : _0_17.default,
      },
  _0_17.GET && {
        source     : "src/api/v1/entities/[id].ts?fn=GET",
        method     : "get",
        route      : "/entities/:id",
        path       : "/api/entities/:id",
        url        : "/api/entities/:id",
        cb         : _0_17.GET,
      },
  _0_17.PUT && {
        source     : "src/api/v1/entities/[id].ts?fn=PUT",
        method     : "put",
        route      : "/entities/:id",
        path       : "/api/entities/:id",
        url        : "/api/entities/:id",
        cb         : _0_17.PUT,
      },
  _0_17.POST && {
        source     : "src/api/v1/entities/[id].ts?fn=POST",
        method     : "post",
        route      : "/entities/:id",
        path       : "/api/entities/:id",
        url        : "/api/entities/:id",
        cb         : _0_17.POST,
      },
  _0_17.PATCH && {
        source     : "src/api/v1/entities/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/entities/:id",
        path       : "/api/entities/:id",
        url        : "/api/entities/:id",
        cb         : _0_17.PATCH,
      },
  _0_17.DELETE && {
        source     : "src/api/v1/entities/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/entities/:id",
        path       : "/api/entities/:id",
        url        : "/api/entities/:id",
        cb         : _0_17.DELETE,
      },
  _0_18.default && {
        source     : "src/api/v1/evidences/index.ts?fn=default",
        method     : "use",
        route      : "/evidences/",
        path       : "/api/evidences/",
        url        : "/api/evidences/",
        cb         : _0_18.default,
      },
  _0_18.GET && {
        source     : "src/api/v1/evidences/index.ts?fn=GET",
        method     : "get",
        route      : "/evidences/",
        path       : "/api/evidences/",
        url        : "/api/evidences/",
        cb         : _0_18.GET,
      },
  _0_18.PUT && {
        source     : "src/api/v1/evidences/index.ts?fn=PUT",
        method     : "put",
        route      : "/evidences/",
        path       : "/api/evidences/",
        url        : "/api/evidences/",
        cb         : _0_18.PUT,
      },
  _0_18.POST && {
        source     : "src/api/v1/evidences/index.ts?fn=POST",
        method     : "post",
        route      : "/evidences/",
        path       : "/api/evidences/",
        url        : "/api/evidences/",
        cb         : _0_18.POST,
      },
  _0_18.PATCH && {
        source     : "src/api/v1/evidences/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/evidences/",
        path       : "/api/evidences/",
        url        : "/api/evidences/",
        cb         : _0_18.PATCH,
      },
  _0_18.DELETE && {
        source     : "src/api/v1/evidences/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/evidences/",
        path       : "/api/evidences/",
        url        : "/api/evidences/",
        cb         : _0_18.DELETE,
      },
  _0_19.default && {
        source     : "src/api/v1/evidences/[id].ts?fn=default",
        method     : "use",
        route      : "/evidences/:id",
        path       : "/api/evidences/:id",
        url        : "/api/evidences/:id",
        cb         : _0_19.default,
      },
  _0_19.GET && {
        source     : "src/api/v1/evidences/[id].ts?fn=GET",
        method     : "get",
        route      : "/evidences/:id",
        path       : "/api/evidences/:id",
        url        : "/api/evidences/:id",
        cb         : _0_19.GET,
      },
  _0_19.PUT && {
        source     : "src/api/v1/evidences/[id].ts?fn=PUT",
        method     : "put",
        route      : "/evidences/:id",
        path       : "/api/evidences/:id",
        url        : "/api/evidences/:id",
        cb         : _0_19.PUT,
      },
  _0_19.POST && {
        source     : "src/api/v1/evidences/[id].ts?fn=POST",
        method     : "post",
        route      : "/evidences/:id",
        path       : "/api/evidences/:id",
        url        : "/api/evidences/:id",
        cb         : _0_19.POST,
      },
  _0_19.PATCH && {
        source     : "src/api/v1/evidences/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/evidences/:id",
        path       : "/api/evidences/:id",
        url        : "/api/evidences/:id",
        cb         : _0_19.PATCH,
      },
  _0_19.DELETE && {
        source     : "src/api/v1/evidences/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/evidences/:id",
        path       : "/api/evidences/:id",
        url        : "/api/evidences/:id",
        cb         : _0_19.DELETE,
      },
  _0_20.default && {
        source     : "src/api/v1/grade/index.ts?fn=default",
        method     : "use",
        route      : "/grade/",
        path       : "/api/grade/",
        url        : "/api/grade/",
        cb         : _0_20.default,
      },
  _0_20.GET && {
        source     : "src/api/v1/grade/index.ts?fn=GET",
        method     : "get",
        route      : "/grade/",
        path       : "/api/grade/",
        url        : "/api/grade/",
        cb         : _0_20.GET,
      },
  _0_20.PUT && {
        source     : "src/api/v1/grade/index.ts?fn=PUT",
        method     : "put",
        route      : "/grade/",
        path       : "/api/grade/",
        url        : "/api/grade/",
        cb         : _0_20.PUT,
      },
  _0_20.POST && {
        source     : "src/api/v1/grade/index.ts?fn=POST",
        method     : "post",
        route      : "/grade/",
        path       : "/api/grade/",
        url        : "/api/grade/",
        cb         : _0_20.POST,
      },
  _0_20.PATCH && {
        source     : "src/api/v1/grade/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/grade/",
        path       : "/api/grade/",
        url        : "/api/grade/",
        cb         : _0_20.PATCH,
      },
  _0_20.DELETE && {
        source     : "src/api/v1/grade/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/grade/",
        path       : "/api/grade/",
        url        : "/api/grade/",
        cb         : _0_20.DELETE,
      },
  _0_21.default && {
        source     : "src/api/v1/grade/[id].ts?fn=default",
        method     : "use",
        route      : "/grade/:id",
        path       : "/api/grade/:id",
        url        : "/api/grade/:id",
        cb         : _0_21.default,
      },
  _0_21.GET && {
        source     : "src/api/v1/grade/[id].ts?fn=GET",
        method     : "get",
        route      : "/grade/:id",
        path       : "/api/grade/:id",
        url        : "/api/grade/:id",
        cb         : _0_21.GET,
      },
  _0_21.PUT && {
        source     : "src/api/v1/grade/[id].ts?fn=PUT",
        method     : "put",
        route      : "/grade/:id",
        path       : "/api/grade/:id",
        url        : "/api/grade/:id",
        cb         : _0_21.PUT,
      },
  _0_21.POST && {
        source     : "src/api/v1/grade/[id].ts?fn=POST",
        method     : "post",
        route      : "/grade/:id",
        path       : "/api/grade/:id",
        url        : "/api/grade/:id",
        cb         : _0_21.POST,
      },
  _0_21.PATCH && {
        source     : "src/api/v1/grade/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/grade/:id",
        path       : "/api/grade/:id",
        url        : "/api/grade/:id",
        cb         : _0_21.PATCH,
      },
  _0_21.DELETE && {
        source     : "src/api/v1/grade/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/grade/:id",
        path       : "/api/grade/:id",
        url        : "/api/grade/:id",
        cb         : _0_21.DELETE,
      },
  _0_22.default && {
        source     : "src/api/v1/homicide/index.ts?fn=default",
        method     : "use",
        route      : "/homicide/",
        path       : "/api/homicide/",
        url        : "/api/homicide/",
        cb         : _0_22.default,
      },
  _0_22.GET && {
        source     : "src/api/v1/homicide/index.ts?fn=GET",
        method     : "get",
        route      : "/homicide/",
        path       : "/api/homicide/",
        url        : "/api/homicide/",
        cb         : _0_22.GET,
      },
  _0_22.PUT && {
        source     : "src/api/v1/homicide/index.ts?fn=PUT",
        method     : "put",
        route      : "/homicide/",
        path       : "/api/homicide/",
        url        : "/api/homicide/",
        cb         : _0_22.PUT,
      },
  _0_22.POST && {
        source     : "src/api/v1/homicide/index.ts?fn=POST",
        method     : "post",
        route      : "/homicide/",
        path       : "/api/homicide/",
        url        : "/api/homicide/",
        cb         : _0_22.POST,
      },
  _0_22.PATCH && {
        source     : "src/api/v1/homicide/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/homicide/",
        path       : "/api/homicide/",
        url        : "/api/homicide/",
        cb         : _0_22.PATCH,
      },
  _0_22.DELETE && {
        source     : "src/api/v1/homicide/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/homicide/",
        path       : "/api/homicide/",
        url        : "/api/homicide/",
        cb         : _0_22.DELETE,
      },
  _0_23.default && {
        source     : "src/api/v1/homicide/[id].ts?fn=default",
        method     : "use",
        route      : "/homicide/:id",
        path       : "/api/homicide/:id",
        url        : "/api/homicide/:id",
        cb         : _0_23.default,
      },
  _0_23.GET && {
        source     : "src/api/v1/homicide/[id].ts?fn=GET",
        method     : "get",
        route      : "/homicide/:id",
        path       : "/api/homicide/:id",
        url        : "/api/homicide/:id",
        cb         : _0_23.GET,
      },
  _0_23.PUT && {
        source     : "src/api/v1/homicide/[id].ts?fn=PUT",
        method     : "put",
        route      : "/homicide/:id",
        path       : "/api/homicide/:id",
        url        : "/api/homicide/:id",
        cb         : _0_23.PUT,
      },
  _0_23.POST && {
        source     : "src/api/v1/homicide/[id].ts?fn=POST",
        method     : "post",
        route      : "/homicide/:id",
        path       : "/api/homicide/:id",
        url        : "/api/homicide/:id",
        cb         : _0_23.POST,
      },
  _0_23.PATCH && {
        source     : "src/api/v1/homicide/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/homicide/:id",
        path       : "/api/homicide/:id",
        url        : "/api/homicide/:id",
        cb         : _0_23.PATCH,
      },
  _0_23.DELETE && {
        source     : "src/api/v1/homicide/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/homicide/:id",
        path       : "/api/homicide/:id",
        url        : "/api/homicide/:id",
        cb         : _0_23.DELETE,
      },
  _0_24.default && {
        source     : "src/api/v1/licences/index.ts?fn=default",
        method     : "use",
        route      : "/licences/",
        path       : "/api/licences/",
        url        : "/api/licences/",
        cb         : _0_24.default,
      },
  _0_24.GET && {
        source     : "src/api/v1/licences/index.ts?fn=GET",
        method     : "get",
        route      : "/licences/",
        path       : "/api/licences/",
        url        : "/api/licences/",
        cb         : _0_24.GET,
      },
  _0_24.PUT && {
        source     : "src/api/v1/licences/index.ts?fn=PUT",
        method     : "put",
        route      : "/licences/",
        path       : "/api/licences/",
        url        : "/api/licences/",
        cb         : _0_24.PUT,
      },
  _0_24.POST && {
        source     : "src/api/v1/licences/index.ts?fn=POST",
        method     : "post",
        route      : "/licences/",
        path       : "/api/licences/",
        url        : "/api/licences/",
        cb         : _0_24.POST,
      },
  _0_24.PATCH && {
        source     : "src/api/v1/licences/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/licences/",
        path       : "/api/licences/",
        url        : "/api/licences/",
        cb         : _0_24.PATCH,
      },
  _0_24.DELETE && {
        source     : "src/api/v1/licences/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/licences/",
        path       : "/api/licences/",
        url        : "/api/licences/",
        cb         : _0_24.DELETE,
      },
  _0_25.default && {
        source     : "src/api/v1/licences/[id].ts?fn=default",
        method     : "use",
        route      : "/licences/:id",
        path       : "/api/licences/:id",
        url        : "/api/licences/:id",
        cb         : _0_25.default,
      },
  _0_25.GET && {
        source     : "src/api/v1/licences/[id].ts?fn=GET",
        method     : "get",
        route      : "/licences/:id",
        path       : "/api/licences/:id",
        url        : "/api/licences/:id",
        cb         : _0_25.GET,
      },
  _0_25.PUT && {
        source     : "src/api/v1/licences/[id].ts?fn=PUT",
        method     : "put",
        route      : "/licences/:id",
        path       : "/api/licences/:id",
        url        : "/api/licences/:id",
        cb         : _0_25.PUT,
      },
  _0_25.POST && {
        source     : "src/api/v1/licences/[id].ts?fn=POST",
        method     : "post",
        route      : "/licences/:id",
        path       : "/api/licences/:id",
        url        : "/api/licences/:id",
        cb         : _0_25.POST,
      },
  _0_25.PATCH && {
        source     : "src/api/v1/licences/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/licences/:id",
        path       : "/api/licences/:id",
        url        : "/api/licences/:id",
        cb         : _0_25.PATCH,
      },
  _0_25.DELETE && {
        source     : "src/api/v1/licences/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/licences/:id",
        path       : "/api/licences/:id",
        url        : "/api/licences/:id",
        cb         : _0_25.DELETE,
      },
  _0_26.default && {
        source     : "src/api/v1/reports/index.ts?fn=default",
        method     : "use",
        route      : "/reports/",
        path       : "/api/reports/",
        url        : "/api/reports/",
        cb         : _0_26.default,
      },
  _0_26.GET && {
        source     : "src/api/v1/reports/index.ts?fn=GET",
        method     : "get",
        route      : "/reports/",
        path       : "/api/reports/",
        url        : "/api/reports/",
        cb         : _0_26.GET,
      },
  _0_26.PUT && {
        source     : "src/api/v1/reports/index.ts?fn=PUT",
        method     : "put",
        route      : "/reports/",
        path       : "/api/reports/",
        url        : "/api/reports/",
        cb         : _0_26.PUT,
      },
  _0_26.POST && {
        source     : "src/api/v1/reports/index.ts?fn=POST",
        method     : "post",
        route      : "/reports/",
        path       : "/api/reports/",
        url        : "/api/reports/",
        cb         : _0_26.POST,
      },
  _0_26.PATCH && {
        source     : "src/api/v1/reports/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/reports/",
        path       : "/api/reports/",
        url        : "/api/reports/",
        cb         : _0_26.PATCH,
      },
  _0_26.DELETE && {
        source     : "src/api/v1/reports/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/reports/",
        path       : "/api/reports/",
        url        : "/api/reports/",
        cb         : _0_26.DELETE,
      },
  _0_27.default && {
        source     : "src/api/v1/reports/[id].ts?fn=default",
        method     : "use",
        route      : "/reports/:id",
        path       : "/api/reports/:id",
        url        : "/api/reports/:id",
        cb         : _0_27.default,
      },
  _0_27.GET && {
        source     : "src/api/v1/reports/[id].ts?fn=GET",
        method     : "get",
        route      : "/reports/:id",
        path       : "/api/reports/:id",
        url        : "/api/reports/:id",
        cb         : _0_27.GET,
      },
  _0_27.PUT && {
        source     : "src/api/v1/reports/[id].ts?fn=PUT",
        method     : "put",
        route      : "/reports/:id",
        path       : "/api/reports/:id",
        url        : "/api/reports/:id",
        cb         : _0_27.PUT,
      },
  _0_27.POST && {
        source     : "src/api/v1/reports/[id].ts?fn=POST",
        method     : "post",
        route      : "/reports/:id",
        path       : "/api/reports/:id",
        url        : "/api/reports/:id",
        cb         : _0_27.POST,
      },
  _0_27.PATCH && {
        source     : "src/api/v1/reports/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/reports/:id",
        path       : "/api/reports/:id",
        url        : "/api/reports/:id",
        cb         : _0_27.PATCH,
      },
  _0_27.DELETE && {
        source     : "src/api/v1/reports/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/reports/:id",
        path       : "/api/reports/:id",
        url        : "/api/reports/:id",
        cb         : _0_27.DELETE,
      },
  _0_28.default && {
        source     : "src/api/v1/sanctions/index.ts?fn=default",
        method     : "use",
        route      : "/sanctions/",
        path       : "/api/sanctions/",
        url        : "/api/sanctions/",
        cb         : _0_28.default,
      },
  _0_28.GET && {
        source     : "src/api/v1/sanctions/index.ts?fn=GET",
        method     : "get",
        route      : "/sanctions/",
        path       : "/api/sanctions/",
        url        : "/api/sanctions/",
        cb         : _0_28.GET,
      },
  _0_28.PUT && {
        source     : "src/api/v1/sanctions/index.ts?fn=PUT",
        method     : "put",
        route      : "/sanctions/",
        path       : "/api/sanctions/",
        url        : "/api/sanctions/",
        cb         : _0_28.PUT,
      },
  _0_28.POST && {
        source     : "src/api/v1/sanctions/index.ts?fn=POST",
        method     : "post",
        route      : "/sanctions/",
        path       : "/api/sanctions/",
        url        : "/api/sanctions/",
        cb         : _0_28.POST,
      },
  _0_28.PATCH && {
        source     : "src/api/v1/sanctions/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/sanctions/",
        path       : "/api/sanctions/",
        url        : "/api/sanctions/",
        cb         : _0_28.PATCH,
      },
  _0_28.DELETE && {
        source     : "src/api/v1/sanctions/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/sanctions/",
        path       : "/api/sanctions/",
        url        : "/api/sanctions/",
        cb         : _0_28.DELETE,
      },
  _0_29.default && {
        source     : "src/api/v1/sanctions/[id].ts?fn=default",
        method     : "use",
        route      : "/sanctions/:id",
        path       : "/api/sanctions/:id",
        url        : "/api/sanctions/:id",
        cb         : _0_29.default,
      },
  _0_29.GET && {
        source     : "src/api/v1/sanctions/[id].ts?fn=GET",
        method     : "get",
        route      : "/sanctions/:id",
        path       : "/api/sanctions/:id",
        url        : "/api/sanctions/:id",
        cb         : _0_29.GET,
      },
  _0_29.PUT && {
        source     : "src/api/v1/sanctions/[id].ts?fn=PUT",
        method     : "put",
        route      : "/sanctions/:id",
        path       : "/api/sanctions/:id",
        url        : "/api/sanctions/:id",
        cb         : _0_29.PUT,
      },
  _0_29.POST && {
        source     : "src/api/v1/sanctions/[id].ts?fn=POST",
        method     : "post",
        route      : "/sanctions/:id",
        path       : "/api/sanctions/:id",
        url        : "/api/sanctions/:id",
        cb         : _0_29.POST,
      },
  _0_29.PATCH && {
        source     : "src/api/v1/sanctions/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/sanctions/:id",
        path       : "/api/sanctions/:id",
        url        : "/api/sanctions/:id",
        cb         : _0_29.PATCH,
      },
  _0_29.DELETE && {
        source     : "src/api/v1/sanctions/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/sanctions/:id",
        path       : "/api/sanctions/:id",
        url        : "/api/sanctions/:id",
        cb         : _0_29.DELETE,
      },
  _0_30.default && {
        source     : "src/api/v1/suspects/index.ts?fn=default",
        method     : "use",
        route      : "/suspects/",
        path       : "/api/suspects/",
        url        : "/api/suspects/",
        cb         : _0_30.default,
      },
  _0_30.GET && {
        source     : "src/api/v1/suspects/index.ts?fn=GET",
        method     : "get",
        route      : "/suspects/",
        path       : "/api/suspects/",
        url        : "/api/suspects/",
        cb         : _0_30.GET,
      },
  _0_30.PUT && {
        source     : "src/api/v1/suspects/index.ts?fn=PUT",
        method     : "put",
        route      : "/suspects/",
        path       : "/api/suspects/",
        url        : "/api/suspects/",
        cb         : _0_30.PUT,
      },
  _0_30.POST && {
        source     : "src/api/v1/suspects/index.ts?fn=POST",
        method     : "post",
        route      : "/suspects/",
        path       : "/api/suspects/",
        url        : "/api/suspects/",
        cb         : _0_30.POST,
      },
  _0_30.PATCH && {
        source     : "src/api/v1/suspects/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/suspects/",
        path       : "/api/suspects/",
        url        : "/api/suspects/",
        cb         : _0_30.PATCH,
      },
  _0_30.DELETE && {
        source     : "src/api/v1/suspects/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/suspects/",
        path       : "/api/suspects/",
        url        : "/api/suspects/",
        cb         : _0_30.DELETE,
      },
  _0_31.default && {
        source     : "src/api/v1/suspects/[id].ts?fn=default",
        method     : "use",
        route      : "/suspects/:id",
        path       : "/api/suspects/:id",
        url        : "/api/suspects/:id",
        cb         : _0_31.default,
      },
  _0_31.GET && {
        source     : "src/api/v1/suspects/[id].ts?fn=GET",
        method     : "get",
        route      : "/suspects/:id",
        path       : "/api/suspects/:id",
        url        : "/api/suspects/:id",
        cb         : _0_31.GET,
      },
  _0_31.PUT && {
        source     : "src/api/v1/suspects/[id].ts?fn=PUT",
        method     : "put",
        route      : "/suspects/:id",
        path       : "/api/suspects/:id",
        url        : "/api/suspects/:id",
        cb         : _0_31.PUT,
      },
  _0_31.POST && {
        source     : "src/api/v1/suspects/[id].ts?fn=POST",
        method     : "post",
        route      : "/suspects/:id",
        path       : "/api/suspects/:id",
        url        : "/api/suspects/:id",
        cb         : _0_31.POST,
      },
  _0_31.PATCH && {
        source     : "src/api/v1/suspects/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/suspects/:id",
        path       : "/api/suspects/:id",
        url        : "/api/suspects/:id",
        cb         : _0_31.PATCH,
      },
  _0_31.DELETE && {
        source     : "src/api/v1/suspects/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/suspects/:id",
        path       : "/api/suspects/:id",
        url        : "/api/suspects/:id",
        cb         : _0_31.DELETE,
      },
  _0_32.default && {
        source     : "src/api/v1/weapons/index.ts?fn=default",
        method     : "use",
        route      : "/weapons/",
        path       : "/api/weapons/",
        url        : "/api/weapons/",
        cb         : _0_32.default,
      },
  _0_32.GET && {
        source     : "src/api/v1/weapons/index.ts?fn=GET",
        method     : "get",
        route      : "/weapons/",
        path       : "/api/weapons/",
        url        : "/api/weapons/",
        cb         : _0_32.GET,
      },
  _0_32.PUT && {
        source     : "src/api/v1/weapons/index.ts?fn=PUT",
        method     : "put",
        route      : "/weapons/",
        path       : "/api/weapons/",
        url        : "/api/weapons/",
        cb         : _0_32.PUT,
      },
  _0_32.POST && {
        source     : "src/api/v1/weapons/index.ts?fn=POST",
        method     : "post",
        route      : "/weapons/",
        path       : "/api/weapons/",
        url        : "/api/weapons/",
        cb         : _0_32.POST,
      },
  _0_32.PATCH && {
        source     : "src/api/v1/weapons/index.ts?fn=PATCH",
        method     : "patch",
        route      : "/weapons/",
        path       : "/api/weapons/",
        url        : "/api/weapons/",
        cb         : _0_32.PATCH,
      },
  _0_32.DELETE && {
        source     : "src/api/v1/weapons/index.ts?fn=DELETE",
        method     : "delete",
        route      : "/weapons/",
        path       : "/api/weapons/",
        url        : "/api/weapons/",
        cb         : _0_32.DELETE,
      },
  _0_33.default && {
        source     : "src/api/v1/weapons/[id].ts?fn=default",
        method     : "use",
        route      : "/weapons/:id",
        path       : "/api/weapons/:id",
        url        : "/api/weapons/:id",
        cb         : _0_33.default,
      },
  _0_33.GET && {
        source     : "src/api/v1/weapons/[id].ts?fn=GET",
        method     : "get",
        route      : "/weapons/:id",
        path       : "/api/weapons/:id",
        url        : "/api/weapons/:id",
        cb         : _0_33.GET,
      },
  _0_33.PUT && {
        source     : "src/api/v1/weapons/[id].ts?fn=PUT",
        method     : "put",
        route      : "/weapons/:id",
        path       : "/api/weapons/:id",
        url        : "/api/weapons/:id",
        cb         : _0_33.PUT,
      },
  _0_33.POST && {
        source     : "src/api/v1/weapons/[id].ts?fn=POST",
        method     : "post",
        route      : "/weapons/:id",
        path       : "/api/weapons/:id",
        url        : "/api/weapons/:id",
        cb         : _0_33.POST,
      },
  _0_33.PATCH && {
        source     : "src/api/v1/weapons/[id].ts?fn=PATCH",
        method     : "patch",
        route      : "/weapons/:id",
        path       : "/api/weapons/:id",
        url        : "/api/weapons/:id",
        cb         : _0_33.PATCH,
      },
  _0_33.DELETE && {
        source     : "src/api/v1/weapons/[id].ts?fn=DELETE",
        method     : "delete",
        route      : "/weapons/:id",
        path       : "/api/weapons/:id",
        url        : "/api/weapons/:id",
        cb         : _0_33.DELETE,
      }
].filter(it => it);

export const routers = internal.map((it) => {
  const { method, path, route, url, source } = it;
  return { method, url, path, route, source };
});

export const endpoints = internal.map(
  (it) => it.method?.toUpperCase() + "\t" + it.url
);

export const applyRouters = (applyRouter) => {
  internal.forEach((it) => {
    it.cb = configure.callbackBefore?.(it.cb, it) || it.cb;
    applyRouter(it);
  });
};

